---
name: MMS-Parser
version: 0.1.0
author:
  - 'Flavio Poletti <flavio [at] polettix [dot] it>'
abstract: parsing facilities for binary MMS messages
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Slurp: 0
  Parse::RecDescent: 0
  Path::Class: 0
  Test::More: 0
  version: 0
provides:
  MMS::Parser:
    file: lib/MMS/Parser.pm
    version: 0.1.0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
